### ISSUE TITLE
Unexpected token =>

### ISSUE THREAD

**Issue by butaixianran** [aaronpowell/linq-in-javascript#4]
hi, I got a Lambda Expression error when trying it: 

``` javascript
//test.js
var linq = require('linq-es6');
var items = [1, 2, 3, 4, 5, 6].asEnumerable();
for (let item in items.where(x => x % 2).select(x => x + 1))
    console.log(item);
```

Then I got:  Unexpected token =>. 
Seems it doesn't have functions to parse lambda expressions?

What should I do to make this work? 
Thanks

**Comment by aaronpowell** [comment]
LINQ in JavaScript uses a combination of [Arrow Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) and [Generator Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*), neither of which are classed as stable in v8 and on Node.js they are behind the `--harmony` flag (although I'm not 100% sure about Arrow Functions). If you're using io.js then generators are enabled by default but arrow functions aren't (see [io.js ES6 features](https://iojs.org/en/es6.html)).

To use this library in applications today you're best running it through a transpiler such as [Babel](http://babeljs.io/) which can be plugged into grunt/gulp/etc quite simply.

**Comment by butaixianran** [comment]
thanks for your reply, I'm using iojs, I just find out arrow functions are still not available even with --harmony flag. I'll try which flag gonna work, thanks again.

**Comment by aaronpowell** [comment]
For io.js you need `--harmony_arrow_functions` as they consider them not stable enough to enable by default from v8
